# version: '3.8'

# services:
#   db:
#     image: mysql:8.0
#     container_name: taste_db
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: taste_of_caribbean
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

#   server:
#     build: .
#     container_name: backend_server
#     ports:
#       - "5001:5000"
#     environment:
#       - DB_HOST=db
#       - DB_NAME=taste_of_caribbean
#       - DB_USER=root
#       - DB_PASS=rootpassword
#       - PORT=5000
#       - NODE_ENV=development
#     depends_on:
#       - db
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules

# volumes:
#   mysql_data:

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
services:
  server:
    image: totc
    container_name: backend_server
    build: .
    ports:
      - "5001:5000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge