# version: '3.8'

# services:
#   db:
#     image: mysql:8.0
#     container_name: taste_db
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: taste_of_caribbean
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

#   server:
#     build: .
#     container_name: backend_server
#     ports:
#       - "5001:5000"
#     environment:
#       - DB_HOST=db
#       - DB_NAME=taste_of_caribbean
#       - DB_USER=root
#       - DB_PASS=rootpassword
#       - PORT=5000
#       - NODE_ENV=development
#     depends_on:
#       - db
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules

# volumes:
#   mysql_data:

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
version: '3.8'

services:
  server:
    image: totc
    container_name: backend_server
    build: .
    ports:
      - "5001:5000"
    environment:
      # AWS RDS CONNECTION
      DB_HOST: toc-dev.chaqko2e2i9g.us-east-1.rds.amazonaws.com
      DB_NAME: totc
      DB_USER: toc_dev
      DB_PASS: toc2024!
      DB_PORT: 3306

      # SERVER
      PORT: 5000
      NODE_ENV: development

      # BCRYPT
      BCRYPT_SALT_ROUNDS: 10

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    # Allows backend to restart if it crashes
    restart: unless-stopped

