version: '1.0'

services:
  backend_server:
    image: backend_server       # Use the image you already built
    container_name: backend_server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development   # Or production when needed
    env_file:
      - .env                    # Environment variables file
    ports:
      - "5001:5000"             # Map host port 5000 to container port 5000
    restart: unless-stopped
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
